name: TruffleHog

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --config=generic.yml --results=verified,unverified,unknown
